apiVersion: v1
kind: Deployment

metadata:
  name: pass-in-deployment
  label:
    app: pass-in

spec:
  replicas: 5
  selector:
    matchLabels:
      app: pass-in
  template:
    metadata:
      labels:
        app: pass-in
    spec:
      containers:
        - name: pass-in
          image: devpedrohb/nlw-unite:2359810
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: url
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: nlw-env
                  key: url
          ports:
            - containerPort: 3333
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 512Mi
